// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.hiroshimeow.private_vault_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WorkProfileApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NativeWorkProfileState(val raw: Int) {
  UNSUPPORTED(0),
  ABSENT(1),
  PROVISIONING(2),
  READY(3),
  QUIET(4),
  CONFLICTING_PROFILE(5),
  POLICY_DENIED(6);

  companion object {
    fun ofRaw(raw: Int): NativeWorkProfileState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeCloneEligibility(val raw: Int) {
  ELIGIBLE(0),
  ALREADY_INSTALLED(1),
  SYSTEM_APP(2),
  PACKAGE_INELIGIBLE(3),
  STORE_FALLBACK_REQUIRED(4),
  UNSUPPORTED(5);

  companion object {
    fun ofRaw(raw: Int): NativeCloneEligibility? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeWorkProfileErrorCode(val raw: Int) {
  UNSUPPORTED(0),
  POLICY_DENIED(1),
  PROFILE_ABSENT(2),
  CONFLICTING_PROFILE(3),
  USER_ACTION_REQUIRED(4),
  PACKAGE_INELIGIBLE(5),
  INSTALLER_FAILURE(6),
  STORE_FALLBACK_REQUIRED(7),
  BRIDGE_TIMEOUT(8),
  OEM_UNSUPPORTED(9),
  UNAUTHORIZED(10);

  companion object {
    fun ofRaw(raw: Int): NativeWorkProfileErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeWorkProfileCapability (
  val supported: Boolean,
  val provisioningAllowed: Boolean,
  val profileState: NativeWorkProfileState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeWorkProfileCapability {
      val supported = pigeonVar_list[0] as Boolean
      val provisioningAllowed = pigeonVar_list[1] as Boolean
      val profileState = pigeonVar_list[2] as NativeWorkProfileState
      return NativeWorkProfileCapability(supported, provisioningAllowed, profileState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supported,
      provisioningAllowed,
      profileState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeWorkProfileCapability
    return WorkProfileApiPigeonUtils.deepEquals(this.supported, other.supported) && WorkProfileApiPigeonUtils.deepEquals(this.provisioningAllowed, other.provisioningAllowed) && WorkProfileApiPigeonUtils.deepEquals(this.profileState, other.profileState)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.supported)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.provisioningAllowed)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.profileState)
    return result
  }
  override fun toString(): String {
    return "NativeWorkProfileCapability(supported=$supported, provisioningAllowed=$provisioningAllowed, profileState=$profileState)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeManagedAppState (
  val packageName: String,
  val label: String,
  val presentPersonal: Boolean,
  val presentWork: Boolean,
  val launchableWork: Boolean,
  val systemApp: Boolean,
  val suspended: Boolean,
  val hidden: Boolean,
  val cloneEligibility: NativeCloneEligibility,
  val installerActionRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeManagedAppState {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val presentPersonal = pigeonVar_list[2] as Boolean
      val presentWork = pigeonVar_list[3] as Boolean
      val launchableWork = pigeonVar_list[4] as Boolean
      val systemApp = pigeonVar_list[5] as Boolean
      val suspended = pigeonVar_list[6] as Boolean
      val hidden = pigeonVar_list[7] as Boolean
      val cloneEligibility = pigeonVar_list[8] as NativeCloneEligibility
      val installerActionRequired = pigeonVar_list[9] as Boolean
      return NativeManagedAppState(packageName, label, presentPersonal, presentWork, launchableWork, systemApp, suspended, hidden, cloneEligibility, installerActionRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      presentPersonal,
      presentWork,
      launchableWork,
      systemApp,
      suspended,
      hidden,
      cloneEligibility,
      installerActionRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeManagedAppState
    return WorkProfileApiPigeonUtils.deepEquals(this.packageName, other.packageName) && WorkProfileApiPigeonUtils.deepEquals(this.label, other.label) && WorkProfileApiPigeonUtils.deepEquals(this.presentPersonal, other.presentPersonal) && WorkProfileApiPigeonUtils.deepEquals(this.presentWork, other.presentWork) && WorkProfileApiPigeonUtils.deepEquals(this.launchableWork, other.launchableWork) && WorkProfileApiPigeonUtils.deepEquals(this.systemApp, other.systemApp) && WorkProfileApiPigeonUtils.deepEquals(this.suspended, other.suspended) && WorkProfileApiPigeonUtils.deepEquals(this.hidden, other.hidden) && WorkProfileApiPigeonUtils.deepEquals(this.cloneEligibility, other.cloneEligibility) && WorkProfileApiPigeonUtils.deepEquals(this.installerActionRequired, other.installerActionRequired)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.label)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.presentPersonal)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.presentWork)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.launchableWork)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.systemApp)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.suspended)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.hidden)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.cloneEligibility)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.installerActionRequired)
    return result
  }
  override fun toString(): String {
    return "NativeManagedAppState(packageName=$packageName, label=$label, presentPersonal=$presentPersonal, presentWork=$presentWork, launchableWork=$launchableWork, systemApp=$systemApp, suspended=$suspended, hidden=$hidden, cloneEligibility=$cloneEligibility, installerActionRequired=$installerActionRequired)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeOperationResult (
  val ok: Boolean,
  val errorCode: NativeWorkProfileErrorCode? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeOperationResult {
      val ok = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as NativeWorkProfileErrorCode?
      val message = pigeonVar_list[2] as String?
      return NativeOperationResult(ok, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeOperationResult
    return WorkProfileApiPigeonUtils.deepEquals(this.ok, other.ok) && WorkProfileApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && WorkProfileApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.ok)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + WorkProfileApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "NativeOperationResult(ok=$ok, errorCode=$errorCode, message=$message)"
  }
}
private open class WorkProfileApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeWorkProfileState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCloneEligibility.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeWorkProfileErrorCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeWorkProfileCapability.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeManagedAppState.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeOperationResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeWorkProfileState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCloneEligibility -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeWorkProfileErrorCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NativeWorkProfileCapability -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeManagedAppState -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeOperationResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WorkProfileHostApi {
  fun getCapability(): NativeWorkProfileCapability
  fun getProfileState(): NativeWorkProfileState
  fun startProvisioning(callback: (Result<NativeOperationResult>) -> Unit)
  fun listPersonalApps(): List<NativeManagedAppState>
  fun listWorkApps(callback: (Result<List<NativeManagedAppState>>) -> Unit)
  fun getAppState(packageName: String, callback: (Result<NativeManagedAppState?>) -> Unit)
  fun cloneToWorkProfile(packageName: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun launchWorkApp(packageName: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun shareVaultFileToWorkApp(packageName: String, stagedFileName: String, mimeType: String, displayName: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun setSuspended(packageName: String, suspended: Boolean, callback: (Result<NativeOperationResult>) -> Unit)
  fun setHidden(packageName: String, hidden: Boolean, callback: (Result<NativeOperationResult>) -> Unit)
  fun uninstallWorkApp(packageName: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun destroyWorkProfile(callback: (Result<NativeOperationResult>) -> Unit)

  companion object {
    /** The codec used by WorkProfileHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WorkProfileApiPigeonCodec()
    }
    /** Sets up an instance of `WorkProfileHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WorkProfileHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.getCapability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCapability())
            } catch (exception: Throwable) {
              WorkProfileApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.getProfileState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getProfileState())
            } catch (exception: Throwable) {
              WorkProfileApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.startProvisioning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startProvisioning{ result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.listPersonalApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listPersonalApps())
            } catch (exception: Throwable) {
              WorkProfileApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.listWorkApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listWorkApps{ result: Result<List<NativeManagedAppState>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.getAppState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getAppState(packageNameArg) { result: Result<NativeManagedAppState?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.cloneToWorkProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.cloneToWorkProfile(packageNameArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.launchWorkApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.launchWorkApp(packageNameArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.shareVaultFileToWorkApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val stagedFileNameArg = args[1] as String
            val mimeTypeArg = args[2] as String
            val displayNameArg = args[3] as String
            api.shareVaultFileToWorkApp(packageNameArg, stagedFileNameArg, mimeTypeArg, displayNameArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.setSuspended$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val suspendedArg = args[1] as Boolean
            api.setSuspended(packageNameArg, suspendedArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.setHidden$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val hiddenArg = args[1] as Boolean
            api.setHidden(packageNameArg, hiddenArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.uninstallWorkApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.uninstallWorkApp(packageNameArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.private_vault_mobile.WorkProfileHostApi.destroyWorkProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.destroyWorkProfile{ result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkProfileApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkProfileApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
